### ISSUE TITLE
yibase资源不存在

### ISSUE THREAD

**Issue by GiterRUOK** [chenbimo/yite-cli#2]
`pnpm dlx dloo -t yibase`（npm亦同）
终端报错如下：
ℹ 开发者：陈随易（https://chensuiyi.me）
-----------------------------------------
🚀 ~ main ~ err: ReferenceError: fetch is not defined
    at main (file:///F:/.pnpm-store/v3/tmp/dlx-16604/node_modules/.pnpm/dloo@2.0.2/node_modules/dloo/dloo.js:46:27)
    at file:///F:/.pnpm-store/v3/tmp/dlx-16604/node_modules/.pnpm/dloo@2.0.2/node_modules/dloo/dloo.js:56:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
✖ 资源错误或不存在，请检查版本是否正确

**Comment by chenbimo** [comment]
收到，我看看。
